name: checks
on: { push: {}, pull_request: {} }
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: unjs/setup-jup@85aa1e9e4cd2995fba3bee414cde74bf88637a2c # v1.0.0
      - run: pnpm typecheck
      - run: pnpm vitest --coverage
      - run: pnpm run lint
      # - uses: codecov/codecov-action@0b35c9ecc4f0529d0eb674914510c22f85b196b4 # v7.1.0
      #   with: { token: "${{ secrets.CODECOV_TOKEN }}" }
